apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
// const request = require('supertest');
// const app = require('../index.js');

// describe('GET /will', function() {
//     it('responds with hello world', function(done) {
//         request(app)
//             .get('/will')
//             .expect(200) // Expected HTTP status code
//             .expect({ response: 'Hello World' }) // Expected response JSON object
//             .end(done);
//     });
// });
